// Real Seed Data Extracted from Excel Workbook "ONUADO NA EYE ACCOUNT.xlsx"
// Total Verified Members: 24

const INITIAL_MEMBERS = [
  {
    "id": "m-001",
    "excel_member_id": "ONY-001",
    "member_no": 1,
    "full_name": "Alex Ackah",
    "name_in_capitals": "ALEX ACKAH",
    "title": "Elder",
    "position": "Youth Chairman",
    "branch": "Takoradi",
    "date_joined": "January 2024",
    "phone_number": "0243430617",
    "phone_number_2": "",
    "house_no": "6A/5A Airport Ridge",
    "gps_address": "",
    "town": "Takoradi",
    "email": "alexackah26@gmail.com",
    "ghana_card": "GHA-720659099-3",
    "occupation": "Driver",
    "place_of_work": "Takoradi",
    "date_of_birth": "May 1982",
    "place_of_birth": "Asankragwa",
    "hometown": "Wassa Daurampong",
    "district": "Amanfie East",
    "region": "Central",
    "tribe": "Wassa",
    "next_of_kin": "Kwabena Boafo Ackah",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "054 396 8936",
    "marital_status": "Married",
    "spouse_name": "Sarah Amoakoah",
    "spouse_contact": "024 937 8595",
    "children_count": "",
    "father_name": "Peter Kofi Obeng",
    "father_contact": "053 835 8530",
    "mother_name": "Akua Bomo",
    "mother_contact": "055 621 2318",
    "reg_fees": 200,
    "dues_paid": 3000,
    "levy_paid": 700,
    "total_payments": 3900,
    "dues_fee_required": 3300,
    "shares_dividends": 60,
    "shares_value": 3035.062385321101,
    "treasurer_bill": 2.1460892049127342,
    "shares_holding": 3037.2084745260136,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-002",
    "excel_member_id": "ONY-002",
    "member_no": 2,
    "full_name": "Danso Kingsley",
    "name_in_capitals": "DANSO KINGSLEY",
    "title": "Elder",
    "position": "Men's Fellowship Chairman",
    "branch": "Mampong",
    "date_joined": "January 2025",
    "phone_number": "0244991855",
    "phone_number_2": "0208304466",
    "house_no": "M/E 163",
    "gps_address": "E2-0793-9218",
    "town": "Mampong Akuapem",
    "email": "dankings@yahoo.com",
    "ghana_card": "GHA-721930936-4",
    "occupation": "Jackson University College",
    "place_of_work": "Somanya",
    "date_of_birth": "June 1966",
    "place_of_birth": "Mampong Akuapem",
    "hometown": "Akim Asane",
    "district": "Akuapem North",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "Kwadwo Siaw Danso",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "059 531 9840",
    "marital_status": "Married",
    "spouse_name": "Matilda Danso",
    "spouse_contact": "055 031 8985",
    "children_count": "Four",
    "father_name": "Jonathan Danso Siaw",
    "father_contact": "024 214 5516",
    "mother_name": "Leticia Oye Siaw",
    "mother_contact": "020 477 7999",
    "reg_fees": 200,
    "dues_paid": 1500,
    "levy_paid": 100,
    "total_payments": 1800,
    "dues_fee_required": 2400,
    "shares_dividends": 30,
    "shares_value": 1517.5311926605505,
    "treasurer_bill": 56.1690815971359,
    "shares_holding": 1573.7002742576863,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "member"
  },
  {
    "id": "m-003",
    "excel_member_id": "ONY-003",
    "member_no": 3,
    "full_name": "Fanuel Hagan",
    "name_in_capitals": "FANUEL HAGAN",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Mankessim",
    "date_joined": "January 2023",
    "phone_number": "0244181735",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "CF-0627-7085",
    "town": "Mankessim",
    "email": "Fanscoelectricals@gmail.com",
    "ghana_card": "GHA-720503848-4",
    "occupation": "Electrocution",
    "place_of_work": "Mankessim",
    "date_of_birth": "December 1981",
    "place_of_birth": "Assin Ochiso",
    "hometown": "Cape Coast",
    "district": "Fanteman District",
    "region": "Central",
    "tribe": "Fante",
    "next_of_kin": "Elfreda Hagan",
    "next_of_kin_relation": "Daughter",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Regina Hagan",
    "spouse_contact": "054 158 7379",
    "children_count": "",
    "father_name": "Joseph Hagan",
    "father_contact": "059 869 1157",
    "mother_name": "Marry Ackom",
    "mother_contact": "055 510 2666",
    "reg_fees": 200,
    "dues_paid": 3400,
    "levy_paid": 1000,
    "total_payments": 4600,
    "dues_fee_required": 3900,
    "shares_dividends": 68,
    "shares_value": 3439.7373700305807,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4268.092628053198,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-004",
    "excel_member_id": "ONY-004",
    "member_no": 4,
    "full_name": "Frederick Wortey Tawiah",
    "name_in_capitals": "FREDERICK WORTEY TAWIAH",
    "title": "Elder",
    "position": "Church Elder",
    "branch": "Ashaiman",
    "date_joined": "January 2023",
    "phone_number": "0553761600",
    "phone_number_2": "0277749302",
    "house_no": "J4/11",
    "gps_address": "GB-039-6631",
    "town": "Jericho-Ashaiman",
    "email": "fredericktawoah360@gmail,com",
    "ghana_card": "GHA-001371929-4",
    "occupation": "Heavy Duty Technician",
    "place_of_work": "Ashaiman",
    "date_of_birth": "February 1965",
    "place_of_birth": "Kumasi",
    "hometown": "Odumase-Krobo",
    "district": "Lower Manya",
    "region": "Eastern",
    "tribe": "Krobo",
    "next_of_kin": "Ebenezer Angmor Wortey",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Rose Tetteh",
    "spouse_contact": "055 710 3472",
    "children_count": "",
    "father_name": "Simon Kwadjo",
    "father_contact": "",
    "mother_name": "Faati Amadu",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 3400,
    "levy_paid": 1000,
    "total_payments": 4600,
    "dues_fee_required": 3900,
    "shares_dividends": 68,
    "shares_value": 3439.7373700305807,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4268.092628053198,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-005",
    "excel_member_id": "ONY-005",
    "member_no": 5,
    "full_name": "George Yeboah",
    "name_in_capitals": "GEORGE YEBOAH",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Dansoman",
    "date_joined": "January 2025",
    "phone_number": "0501786106",
    "phone_number_2": "0242856642",
    "house_no": "",
    "gps_address": "",
    "town": "",
    "email": "",
    "ghana_card": "",
    "occupation": "",
    "place_of_work": "",
    "date_of_birth": "",
    "place_of_birth": "",
    "hometown": "",
    "district": "",
    "region": "",
    "tribe": "",
    "next_of_kin": "",
    "next_of_kin_relation": "",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "",
    "spouse_contact": "",
    "children_count": "",
    "father_name": "",
    "father_contact": "",
    "mother_name": "",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 200,
    "levy_paid": 100,
    "total_payments": 500,
    "dues_fee_required": 2400,
    "shares_dividends": 0,
    "shares_value": 0,
    "treasurer_bill": 0,
    "shares_holding": 0,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "member"
  },
  {
    "id": "m-006",
    "excel_member_id": "ONY-006",
    "member_no": 6,
    "full_name": "Isaac Darko",
    "name_in_capitals": "ISAAC DARKO",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Nsawam",
    "date_joined": "January 2023",
    "phone_number": "0547261159",
    "phone_number_2": "",
    "house_no": "HH/12B",
    "gps_address": "",
    "town": "Nsawam Adoagyiri",
    "email": "",
    "ghana_card": "GHA-721767934-6",
    "occupation": "Driver",
    "place_of_work": "Accra",
    "date_of_birth": "January 1975",
    "place_of_birth": "Nsawam Adoagyiri",
    "hometown": "Nsawam Adoagyiri",
    "district": "Nsawam Adoagyiri",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "William Obuobi Darko",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "055 443 3909",
    "marital_status": "Married",
    "spouse_name": "Emma Darko",
    "spouse_contact": "055 803 2662",
    "children_count": "Four",
    "father_name": "Opayin Yaw Darko",
    "father_contact": "",
    "mother_name": "Obaapayin Akosua Pokua",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 3900,
    "levy_paid": 800,
    "total_payments": 4900,
    "dues_fee_required": 3900,
    "shares_dividends": 78,
    "shares_value": 3945.581100917431,
    "treasurer_bill": 2.1460892049127342,
    "shares_holding": 3947.7271901223435,
    "father_state": "Alive",
    "mother_state": "Diseased",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-007",
    "excel_member_id": "ONY-007",
    "member_no": 7,
    "full_name": "Isaac Donkor",
    "name_in_capitals": "ISAAC DONKOR",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Suame",
    "date_joined": "January 2024",
    "phone_number": "0243109072",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "AF-0129-3414",
    "town": "Kumasi Suame",
    "email": "donkorisaac1979@gmail.com",
    "ghana_card": "GHA-718421698-0",
    "occupation": "Businessman",
    "place_of_work": "Kumasi",
    "date_of_birth": "June 1979",
    "place_of_birth": "Akim Abuoso",
    "hometown": "Atwima Bebu",
    "district": "Ateima Kwanwoma",
    "region": "Ashanti",
    "tribe": "Asante",
    "next_of_kin": "Era Donkor",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "055 546 0838",
    "marital_status": "Married",
    "spouse_name": "Era Donkor",
    "spouse_contact": "055 546 0838",
    "children_count": "",
    "father_name": "Kennedy Eddy Donkor",
    "father_contact": "054 553 7670",
    "mother_name": "Ama Fosuaa",
    "mother_contact": "024 327 5855",
    "reg_fees": 200,
    "dues_paid": 3300,
    "levy_paid": 100,
    "total_payments": 3600,
    "dues_fee_required": 3300,
    "shares_dividends": 66,
    "shares_value": 3338.5686238532107,
    "treasurer_bill": 56.1690815971359,
    "shares_holding": 3394.7377054503468,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-008",
    "excel_member_id": "ONY-008",
    "member_no": 8,
    "full_name": "John Aidoo",
    "name_in_capitals": "JOHN AIDOO",
    "title": "Mr.",
    "position": "Chourester",
    "branch": "Ashaiman",
    "date_joined": "January 2026",
    "phone_number": "0243129927",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "GK-0435-1876",
    "town": "Ashaiman",
    "email": "",
    "ghana_card": "GHA-00137688-3",
    "occupation": "Self Employed",
    "place_of_work": "Katamanso",
    "date_of_birth": "June 1976",
    "place_of_birth": "Abaasa",
    "hometown": "Abaasa",
    "district": "Enyan",
    "region": "Central",
    "tribe": "Fante",
    "next_of_kin": "Michael Aidoo",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Faustina Aidoo",
    "spouse_contact": "054 570 4732",
    "children_count": "Two",
    "father_name": "Opayin Paul Aidoo",
    "father_contact": "024 755 5385",
    "mother_name": "Hannah Onuma",
    "mother_contact": "055 153 0777",
    "reg_fees": 200,
    "dues_paid": 900,
    "levy_paid": 0,
    "total_payments": 1100,
    "dues_fee_required": 1200,
    "shares_dividends": 18,
    "shares_value": 910.5187155963303,
    "treasurer_bill": 0,
    "shares_holding": 910.5187155963303,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-009",
    "excel_member_id": "ONY-009",
    "member_no": 9,
    "full_name": "John Darbo",
    "name_in_capitals": "JOHN DARBO",
    "title": "Elder",
    "position": "Youth Chairman",
    "branch": "Dansoman",
    "date_joined": "January 2025",
    "phone_number": "0557336020",
    "phone_number_2": "0509341027",
    "house_no": "B/71",
    "gps_address": "",
    "town": "Wiabona",
    "email": "JohnDarbo@gmail.com",
    "ghana_card": "GHA-001499499-7",
    "occupation": "Trader",
    "place_of_work": "Accra",
    "date_of_birth": "March 1980",
    "place_of_birth": "Achiase",
    "hometown": "Bomfa Achiase",
    "district": "Asante Akim",
    "region": "Ashanti",
    "tribe": "Asante",
    "next_of_kin": "Ruth Darbo",
    "next_of_kin_relation": "",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Selina Darbo",
    "spouse_contact": "",
    "children_count": "Seven",
    "father_name": "Akwasi Offin",
    "father_contact": "",
    "mother_name": "Afia Kyerewaa",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 350,
    "levy_paid": 100,
    "total_payments": 650,
    "dues_fee_required": 2400,
    "shares_dividends": 0,
    "shares_value": 0,
    "treasurer_bill": 0,
    "shares_holding": 0,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "REMOVED",
    "role": "member"
  },
  {
    "id": "m-010",
    "excel_member_id": "ONY-010",
    "member_no": 10,
    "full_name": "John Ofosuhene Asare",
    "name_in_capitals": "JOHN OFOSUHENE ASARE",
    "title": "Elder",
    "position": "Executive Board Member",
    "branch": "Kotobabi",
    "date_joined": "January 2023",
    "phone_number": "0242927915",
    "phone_number_2": "",
    "house_no": "DE 32 Circle St.",
    "gps_address": "GW-1027-5738",
    "town": "Kotoku Papase",
    "email": "ofosufenejohn@gmail.com",
    "ghana_card": "GHA-722763286-3",
    "occupation": "Building Construction",
    "place_of_work": "Tsado",
    "date_of_birth": "April 1973",
    "place_of_birth": "Akim Swedru",
    "hometown": "Akim Swedru",
    "district": "Briem North",
    "region": "Eastern",
    "tribe": "Akim",
    "next_of_kin": "Simon Ofosuhene",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "053 371 6628",
    "marital_status": "Married",
    "spouse_name": "Mary Ofosuhene",
    "spouse_contact": "054 037 6893",
    "children_count": "",
    "father_name": "Moses Kwame Ofosuhene",
    "father_contact": "",
    "mother_name": "Elizabeth Antwi",
    "mother_contact": "054 328 3970",
    "reg_fees": 200,
    "dues_paid": 3400,
    "levy_paid": 800,
    "total_payments": 4400,
    "dues_fee_required": 3900,
    "shares_dividends": 68,
    "shares_value": 3439.7373700305807,
    "treasurer_bill": 499.8287815126051,
    "shares_holding": 3939.5661515431857,
    "father_state": "Diseased",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "admin"
  },
  {
    "id": "m-011",
    "excel_member_id": "ONY-011",
    "member_no": 11,
    "full_name": "Johnson Wood",
    "name_in_capitals": "JOHNSON WOOD",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Takoradi",
    "date_joined": "January 2023",
    "phone_number": "0240466830",
    "phone_number_2": "",
    "house_no": "Mpintsin New Site",
    "gps_address": "WS-107-326",
    "town": "Takoradi",
    "email": "jbwoode30@gmail.com",
    "ghana_card": "GHA-719844260-5",
    "occupation": "Sales Representative",
    "place_of_work": "Takoradi",
    "date_of_birth": "August 1979",
    "place_of_birth": "Sekondi / Essikado",
    "hometown": "Ajumako Bisease",
    "district": "Ajumako/Enyan/Essiam",
    "region": "Central",
    "tribe": "Fante",
    "next_of_kin": "Sarah Wood",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "024 401 7670",
    "marital_status": "Married",
    "spouse_name": "Sarah Wood",
    "spouse_contact": "024 401 7670",
    "children_count": "",
    "father_name": "Johnson Benjamin Wood",
    "father_contact": "054 851 6251",
    "mother_name": "Kate Ennin",
    "mother_contact": "050 258 3546",
    "reg_fees": 200,
    "dues_paid": 3500,
    "levy_paid": 1000,
    "total_payments": 4700,
    "dues_fee_required": 3900,
    "shares_dividends": 70,
    "shares_value": 3540.906116207951,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4369.2613742305675,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-012",
    "excel_member_id": "ONY-012",
    "member_no": 12,
    "full_name": "Jonas Wereko",
    "name_in_capitals": "JONAS WEREKO",
    "title": "Elder",
    "position": "Church Elder",
    "branch": "Atonsu",
    "date_joined": "January 2023",
    "phone_number": "0244533372",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "",
    "town": "",
    "email": "",
    "ghana_card": "",
    "occupation": "Auto Sprayer",
    "place_of_work": "",
    "date_of_birth": "",
    "place_of_birth": "",
    "hometown": "",
    "district": "",
    "region": "",
    "tribe": "",
    "next_of_kin": "",
    "next_of_kin_relation": "",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "",
    "spouse_contact": "",
    "children_count": "",
    "father_name": "",
    "father_contact": "",
    "mother_name": "",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 3600,
    "levy_paid": 1000,
    "total_payments": 4800,
    "dues_fee_required": 3900,
    "shares_dividends": 72,
    "shares_value": 3642.074862385321,
    "treasurer_bill": 2.1460892049127342,
    "shares_holding": 3644.2209515902337,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-013",
    "excel_member_id": "ONY-013",
    "member_no": 13,
    "full_name": "Jonathan Danso Siaw",
    "name_in_capitals": "JONATHAN DANSO SIAW",
    "title": "Elder",
    "position": "Secretary (Executive Board)",
    "branch": "Aburi",
    "date_joined": "January 2023",
    "phone_number": "0242145516",
    "phone_number_2": "0206145516",
    "house_no": "M/E 163",
    "gps_address": "E2-0793-9515",
    "town": "Mampong Akuapem",
    "email": "idkofisiaw@gmail.com",
    "ghana_card": "GHA-004625185-1",
    "occupation": "Pensioner",
    "place_of_work": "Mampomg Akuapem",
    "date_of_birth": "June 1942",
    "place_of_birth": "Mampomg Akuapem",
    "hometown": "Mampomg Akuapem",
    "district": "Akuapem North",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "Leticia Oye Siaw",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "020 477 999",
    "marital_status": "Married",
    "spouse_name": "Leticia Oye Siaw",
    "spouse_contact": "020 477 999",
    "children_count": "Four",
    "father_name": "Gyan Danso",
    "father_contact": "",
    "mother_name": "Regina Dakoa Dankwa",
    "mother_contact": "024 314 3124",
    "reg_fees": 200,
    "dues_paid": 3900,
    "levy_paid": 800,
    "total_payments": 4900,
    "dues_fee_required": 3900,
    "shares_dividends": 118,
    "shares_value": 5968.956024464832,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 6797.311282487449,
    "father_state": "Diseased",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "admin"
  },
  {
    "id": "m-014",
    "excel_member_id": "ONY-014",
    "member_no": 14,
    "full_name": "Joseph Kofi Amanfo",
    "name_in_capitals": "JOSEPH KOFI AMANFO",
    "title": "Elder",
    "position": "National Youth Chairman",
    "branch": "Odorkor",
    "date_joined": "January 2023",
    "phone_number": "0268713230",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "",
    "town": "",
    "email": "",
    "ghana_card": "",
    "occupation": "",
    "place_of_work": "",
    "date_of_birth": "",
    "place_of_birth": "",
    "hometown": "",
    "district": "",
    "region": "",
    "tribe": "",
    "next_of_kin": "",
    "next_of_kin_relation": "",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "",
    "spouse_contact": "",
    "children_count": "",
    "father_name": "",
    "father_contact": "",
    "mother_name": "",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 1000,
    "levy_paid": 1000,
    "total_payments": 2200,
    "dues_fee_required": 3900,
    "shares_dividends": 0,
    "shares_value": 0,
    "treasurer_bill": 0,
    "shares_holding": 0,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "REMOVED",
    "role": "member"
  },
  {
    "id": "m-015",
    "excel_member_id": "ONY-015",
    "member_no": 15,
    "full_name": "Justice Kojo Acheampong",
    "name_in_capitals": "JUSTICE KOJO ACHEAMPONG",
    "title": "Elder",
    "position": "Youth Chairman",
    "branch": "Kasoa",
    "date_joined": "January 2023",
    "phone_number": "0247505280",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "",
    "town": "Kasoa",
    "email": "justiceacheampong30400@gmail.com",
    "ghana_card": "GHA-719976822-3",
    "occupation": "Boutique",
    "place_of_work": "Kasoa",
    "date_of_birth": "June 1977",
    "place_of_birth": "Gomoa Afransi",
    "hometown": "Gomoa Afransi",
    "district": "Gomoa Central",
    "region": "Central",
    "tribe": "Gomoa",
    "next_of_kin": "Nathanel Acheampong",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "053 506 647",
    "marital_status": "Married",
    "spouse_name": "Hanah Acheampong",
    "spouse_contact": "024 114 7045",
    "children_count": "Four",
    "father_name": "Kojo Acheampong",
    "father_contact": "027 150 6060",
    "mother_name": "Esi Mansah",
    "mother_contact": "055 504 6416",
    "reg_fees": 200,
    "dues_paid": 3000,
    "levy_paid": 1000,
    "total_payments": 4200,
    "dues_fee_required": 3900,
    "shares_dividends": 60,
    "shares_value": 3035.062385321101,
    "treasurer_bill": 772.1861764254808,
    "shares_holding": 3807.248561746582,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "member"
  },
  {
    "id": "m-016",
    "excel_member_id": "ONY-016",
    "member_no": 16,
    "full_name": "Just-Mark Kwabena Quansah",
    "name_in_capitals": "JUST-MARK KWABENA QUANSAH",
    "title": "Elder",
    "position": "P.R.O. (Executive Board)",
    "branch": "Ashaiman",
    "date_joined": "January 2023",
    "phone_number": "0267461029",
    "phone_number_2": "0246528067",
    "house_no": "N/360",
    "gps_address": "GB-0261673",
    "town": "Ashaiman",
    "email": "elderquan7601@gmail.com",
    "ghana_card": "GHA-00134909-6",
    "occupation": "Bakery",
    "place_of_work": "Ashaiman",
    "date_of_birth": "August 1979",
    "place_of_birth": "Shama",
    "hometown": "Shama",
    "district": "Shama District",
    "region": "Central",
    "tribe": "Fante",
    "next_of_kin": "Quansah Jordan Kwame",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Quansah Victoria",
    "spouse_contact": "053 439 6522",
    "children_count": "",
    "father_name": "Nketia Quansah",
    "father_contact": "054 109 9509",
    "mother_name": "Mary Branful",
    "mother_contact": "054 152 4008",
    "reg_fees": 200,
    "dues_paid": 3000,
    "levy_paid": 1000,
    "total_payments": 4200,
    "dues_fee_required": 3900,
    "shares_dividends": 60,
    "shares_value": 3035.062385321101,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 3863.417643343718,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "admin"
  },
  {
    "id": "m-017",
    "excel_member_id": "ONY-017",
    "member_no": 17,
    "full_name": "Maxwell Ofei Siaw",
    "name_in_capitals": "MAXWELL OFEI SIAW",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Teshie",
    "date_joined": "January 2023",
    "phone_number": "0247880895",
    "phone_number_2": "0243783004",
    "house_no": "EC/745 Garden Acres St",
    "gps_address": "GK-0755-5569",
    "town": "Oyibi",
    "email": "cecebunibuni@gnail.com",
    "ghana_card": "GHA-745309113-6",
    "occupation": "Auditor",
    "place_of_work": "Accra High Court",
    "date_of_birth": "May 1982",
    "place_of_birth": "Takoradi",
    "hometown": "Mampomg Akuapem",
    "district": "Akuapem North",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "Cecilia Adofowa Ofei",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "026 286 5288",
    "marital_status": "Married",
    "spouse_name": "Cecilia Adofowa Ofei",
    "spouse_contact": "026 286 5288",
    "children_count": "Four",
    "father_name": "Jonathan Danso Siaw",
    "father_contact": "024 210 5516",
    "mother_name": "Leticia Oye Siaw",
    "mother_contact": "020 477 7999",
    "reg_fees": 200,
    "dues_paid": 3300,
    "levy_paid": 1000,
    "total_payments": 4500,
    "dues_fee_required": 3900,
    "shares_dividends": 66,
    "shares_value": 3338.5686238532107,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4166.923881875828,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "member"
  },
  {
    "id": "m-018",
    "excel_member_id": "ONY-018",
    "member_no": 18,
    "full_name": "Moses Oduro",
    "name_in_capitals": "MOSES ODURO",
    "title": "Elder",
    "position": "President (Executive Board)",
    "branch": "Noyem",
    "date_joined": "January 2023",
    "phone_number": "0203541966",
    "phone_number_2": "0268146137",
    "house_no": "C/8 NOYEM",
    "gps_address": "EX-1532-7443",
    "town": "NOYEM",
    "email": "mosesoduro1966@gmail.com",
    "ghana_card": "GHA-722014751-1",
    "occupation": "Tipper Truck Business",
    "place_of_work": "Noyem",
    "date_of_birth": "November 1962",
    "place_of_birth": "Noyem",
    "hometown": "Noyem",
    "district": "Birim North",
    "region": "Eastern",
    "tribe": "Akim",
    "next_of_kin": "Frederick Oduro",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "Regina Oduro",
    "spouse_contact": "",
    "children_count": "Eight",
    "father_name": "Paul Antwi",
    "father_contact": "",
    "mother_name": "Agatha Forjuor",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 3900,
    "levy_paid": 1000,
    "total_payments": 5100,
    "dues_fee_required": 3900,
    "shares_dividends": 78,
    "shares_value": 3945.581100917431,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4773.936358940047,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "admin"
  },
  {
    "id": "m-019",
    "excel_member_id": "ONY-019",
    "member_no": 19,
    "full_name": "Osei Kwame",
    "name_in_capitals": "OSEI KWAME",
    "title": "Elder",
    "position": "Vice President (Executive Board)",
    "branch": "Kasoa",
    "date_joined": "January 2023",
    "phone_number": "0244283224",
    "phone_number_2": "",
    "house_no": "WL 387/1",
    "gps_address": "CG-0583-8649",
    "town": "Kasoa Ofankor",
    "email": "kenosei1656@gmail,com",
    "ghana_card": "GHA-721203546-3",
    "occupation": "Car Dealer",
    "place_of_work": "Kasoa Ofankor",
    "date_of_birth": "February 1972",
    "place_of_birth": "Kyekyewere",
    "hometown": "Anyinasu",
    "district": "Ejura Sekyere Dumase",
    "region": "Ashanti",
    "tribe": "Ashanti",
    "next_of_kin": "Osei Kenneth Appiah",
    "next_of_kin_relation": "Son",
    "next_of_kin_contact": "059 994 2041",
    "marital_status": "Married",
    "spouse_name": "Theresah Afriyie",
    "spouse_contact": "054 275 0318",
    "children_count": "",
    "father_name": "Kofi Nsia",
    "father_contact": "",
    "mother_name": "Akua Mansah",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 3500,
    "levy_paid": 1000,
    "total_payments": 4700,
    "dues_fee_required": 3900,
    "shares_dividends": 110,
    "shares_value": 5564.281039755351,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 6392.636297777968,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "admin"
  },
  {
    "id": "m-020",
    "excel_member_id": "ONY-020",
    "member_no": 20,
    "full_name": "Peter Kingsford Nkrumah",
    "name_in_capitals": "PETER KINGSFORD NKRUMAH",
    "title": "Elder",
    "position": "Secretary",
    "branch": "Kasoa",
    "date_joined": "January 2023",
    "phone_number": "0543382738",
    "phone_number_2": "",
    "house_no": "K-144/11 UN Guy",
    "gps_address": "CX-132-3953",
    "town": "Kasoa",
    "email": "peterkingsfordnkrumah@gmail.com",
    "ghana_card": "GHA-002364861-6",
    "occupation": "Pensioner",
    "place_of_work": "Kasoa",
    "date_of_birth": "November 1961",
    "place_of_birth": "Amosima",
    "hometown": "Amosima",
    "district": "Abura Aseibu",
    "region": "Central",
    "tribe": "Fante",
    "next_of_kin": "Margaret Nkrumah",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "024 983 6713",
    "marital_status": "Married",
    "spouse_name": "Margaret Nkrumah",
    "spouse_contact": "024 983 6713",
    "children_count": "",
    "father_name": "Matthew K Nkrumah",
    "father_contact": "024 459 1236",
    "mother_name": "Mary Nkrumah (Ekua Akua)",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 900,
    "levy_paid": 1000,
    "total_payments": 2100,
    "dues_fee_required": 3900,
    "shares_dividends": 0,
    "shares_value": 0,
    "treasurer_bill": 0,
    "shares_holding": 0,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "REMOVED",
    "role": "member"
  },
  {
    "id": "m-021",
    "excel_member_id": "ONY-021",
    "member_no": 21,
    "full_name": "Prince Asante Ahwireng",
    "name_in_capitals": "PRINCE ASANTE AHWIRENG",
    "title": "Elder",
    "position": "Treasurer",
    "branch": "Aburi",
    "date_joined": "January 2023",
    "phone_number": "0548645220",
    "phone_number_2": "",
    "house_no": "AW 52/4",
    "gps_address": "E3-007-9789",
    "town": "Aburi",
    "email": "princeahwiren6152@gmail.com",
    "ghana_card": "GHA-722403637-4",
    "occupation": "Welder",
    "place_of_work": "Aburi",
    "date_of_birth": "May 1994",
    "place_of_birth": "Dago",
    "hometown": "Aburi",
    "district": "Akuapem South",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "Ebenezer Ahwireng",
    "next_of_kin_relation": "Brother",
    "next_of_kin_contact": "054 717 6323",
    "marital_status": "Married",
    "spouse_name": "Grace Asante",
    "spouse_contact": "054 570 4701",
    "children_count": "Three",
    "father_name": "Nana Ahwireng",
    "father_contact": "",
    "mother_name": "Gladys Asante",
    "mother_contact": "054 501 5197",
    "reg_fees": 200,
    "dues_paid": 3300,
    "levy_paid": 900,
    "total_payments": 4400,
    "dues_fee_required": 3900,
    "shares_dividends": 66,
    "shares_value": 3338.5686238532107,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4166.923881875828,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "PROBATION",
    "role": "member"
  },
  {
    "id": "m-022",
    "excel_member_id": "ONY-022",
    "member_no": 22,
    "full_name": "Samuel Yaw Nkansah",
    "name_in_capitals": "SAMUEL YAW NKANSAH",
    "title": "Elder",
    "position": "Youth Chairman",
    "branch": "Darkuman",
    "date_joined": "January 2023",
    "phone_number": "0246560312",
    "phone_number_2": "",
    "house_no": "",
    "gps_address": "",
    "town": "",
    "email": "",
    "ghana_card": "",
    "occupation": "Trader in Tiles",
    "place_of_work": "",
    "date_of_birth": "",
    "place_of_birth": "",
    "hometown": "",
    "district": "",
    "region": "",
    "tribe": "",
    "next_of_kin": "",
    "next_of_kin_relation": "",
    "next_of_kin_contact": "",
    "marital_status": "Married",
    "spouse_name": "",
    "spouse_contact": "",
    "children_count": "",
    "father_name": "",
    "father_contact": "",
    "mother_name": "",
    "mother_contact": "",
    "reg_fees": 200,
    "dues_paid": 1700,
    "levy_paid": 700,
    "total_payments": 2600,
    "dues_fee_required": 3900,
    "shares_dividends": 0,
    "shares_value": 0,
    "treasurer_bill": 0,
    "shares_holding": 0,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "REMOVED",
    "role": "member"
  },
  {
    "id": "m-023",
    "excel_member_id": "ONY-023",
    "member_no": 23,
    "full_name": "Vincent Agamatey",
    "name_in_capitals": "VINCENT AGAMATEY",
    "title": "Elder",
    "position": "Treasurer",
    "branch": "Koforidua",
    "date_joined": "January 2023",
    "phone_number": "0244067032",
    "phone_number_2": "",
    "house_no": "Old Dasuoyaa JHS",
    "gps_address": "E2-09390063",
    "town": "Koforidua",
    "email": "Agaagamateyvincent881@gmail.com",
    "ghana_card": "GHA-722583522-4",
    "occupation": "Mason / Tiller",
    "place_of_work": "Koforidua",
    "date_of_birth": "May 1978",
    "place_of_birth": "Tinkon Mile 40",
    "hometown": "Somanya",
    "district": "Yilo Krobo",
    "region": "Eastern",
    "tribe": "Krobo",
    "next_of_kin": "Abigail Agamatey",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "024 722 8692",
    "marital_status": "Married",
    "spouse_name": "Abigail Agamatey",
    "spouse_contact": "024 722 8692",
    "children_count": "",
    "father_name": "Samuel Tetteh",
    "father_contact": "024 844 2609",
    "mother_name": "Victoria Donkor",
    "mother_contact": "054 509 4585",
    "reg_fees": 200,
    "dues_paid": 3700,
    "levy_paid": 1000,
    "total_payments": 4900,
    "dues_fee_required": 3900,
    "shares_dividends": 74,
    "shares_value": 3743.243608562691,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4571.598866585307,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "member"
  },
  {
    "id": "m-024",
    "excel_member_id": "ONY-024",
    "member_no": 24,
    "full_name": "William Kojo Anane",
    "name_in_capitals": "WILLIAM KOJO ANANE",
    "title": "Elder",
    "position": "Executive Board Member",
    "branch": "Ashaiman",
    "date_joined": "January 2023",
    "phone_number": "0269563876",
    "phone_number_2": "0247685316",
    "house_no": "KN/045",
    "gps_address": "GK-0491-5502",
    "town": "Ashaiman",
    "email": "williamsanane497@gmail.com",
    "ghana_card": "GHA-725903330-0",
    "occupation": "Mechanical Engineering",
    "place_of_work": "Ashaiman Middle East",
    "date_of_birth": "October 1978",
    "place_of_birth": "Akosombo",
    "hometown": "Akosombo",
    "district": "Asuogyaman",
    "region": "Eastern",
    "tribe": "Akuapem",
    "next_of_kin": "Margaret Anane",
    "next_of_kin_relation": "Wife",
    "next_of_kin_contact": "024 530 1392",
    "marital_status": "Married",
    "spouse_name": "Margaret Anane",
    "spouse_contact": "024 530 1392",
    "children_count": "Five",
    "father_name": "Seth Sarpong",
    "father_contact": "055 418 5769",
    "mother_name": "Margaret Sarpong",
    "mother_contact": "024 255 4607",
    "reg_fees": 200,
    "dues_paid": 3900,
    "levy_paid": 1000,
    "total_payments": 5100,
    "dues_fee_required": 3900,
    "shares_dividends": 78,
    "shares_value": 3945.581100917431,
    "treasurer_bill": 828.3552580226167,
    "shares_holding": 4773.936358940047,
    "father_state": "Alive",
    "mother_state": "Alive",
    "status": "ACTIVE",
    "role": "admin"
  }
];

const INITIAL_CONTRIBUTIONS = [
  { id: "c-001", member_id: "m-001", amount: 3000, contribution_type: "Monthly Dues", payment_method: "Mobile Money", reference_note: "Dues Settlement (2024-2025)", received_by_name: "Jonathan Danso Siaw", payment_date: "2026-01-15" },
  { id: "c-002", member_id: "m-001", amount: 700, contribution_type: "Special Levy", payment_method: "Mobile Money", reference_note: "1st-7th Levy Installment", received_by_name: "Jonathan Danso Siaw", payment_date: "2026-02-10" },
  { id: "c-003", member_id: "m-018", amount: 3900, contribution_type: "Monthly Dues", payment_method: "Fidelity Bank Transfer", reference_note: "Full Dues Payment 2026", received_by_name: "Osei Kwame", payment_date: "2026-01-10" },
  { id: "c-004", member_id: "m-019", amount: 3900, contribution_type: "Monthly Dues", payment_method: "Mobile Money", reference_note: "Full Dues Payment 2026", received_by_name: "Moses Oduro", payment_date: "2026-01-12" },
  { id: "c-005", member_id: "m-013", amount: 3900, contribution_type: "Monthly Dues", payment_method: "Fidelity Bank Transfer", reference_note: "Full Dues Settlement", received_by_name: "Moses Oduro", payment_date: "2026-01-18" },
  { id: "c-006", member_id: "m-016", amount: 1500, contribution_type: "Monthly Dues", payment_method: "Mobile Money", reference_note: "Dues Installment", received_by_name: "Jonathan Danso Siaw", payment_date: "2026-02-01" },
  { id: "c-007", member_id: "m-024", amount: 3900, contribution_type: "Monthly Dues", payment_method: "Mobile Money", reference_note: "Dues Settlement", received_by_name: "Jonathan Danso Siaw", payment_date: "2026-01-20" }
];

export const getMembers = () => {
  const stored = localStorage.getItem('ony_members');
  if (!stored) {
    localStorage.setItem('ony_members', JSON.stringify(INITIAL_MEMBERS));
    return INITIAL_MEMBERS;
  }
  try {
    return JSON.parse(stored);
  } catch (e) {
    return INITIAL_MEMBERS;
  }
};

export const saveMembers = (members) => {
  localStorage.setItem('ony_members', JSON.stringify(members));
};

export const updateMemberProfile = (memberId, updatedFields) => {
  const members = getMembers();
  const index = members.findIndex(m => m.id === memberId);
  if (index !== -1) {
    members[index] = { ...members[index], ...updatedFields };
    saveMembers(members);
  }
  return members;
};

export const getContributions = () => {
  const stored = localStorage.getItem('ony_contributions');
  if (!stored) {
    localStorage.setItem('ony_contributions', JSON.stringify(INITIAL_CONTRIBUTIONS));
    return INITIAL_CONTRIBUTIONS;
  }
  try {
    return JSON.parse(stored);
  } catch (e) {
    return INITIAL_CONTRIBUTIONS;
  }
};

export const addContribution = (contribution) => {
  const contributions = getContributions();
  const newRecord = {
    id: 'c-' + String(contributions.length + 1).padStart(3, '0'),
    payment_date: new Date().toISOString().split('T')[0],
    ...contribution
  };
  const updated = [newRecord, ...contributions];
  localStorage.setItem('ony_contributions', JSON.stringify(updated));

  // Also update total payments on member
  const members = getMembers();
  const memberIndex = members.findIndex(m => m.id === contribution.member_id);
  if (memberIndex !== -1) {
    const amountNum = parseFloat(contribution.amount) || 0;
    if (contribution.contribution_type === 'Monthly Dues') {
      members[memberIndex].dues_paid = (members[memberIndex].dues_paid || 0) + amountNum;
    } else if (contribution.contribution_type === 'Special Levy') {
      members[memberIndex].levy_paid = (members[memberIndex].levy_paid || 0) + amountNum;
    }
    members[memberIndex].total_payments = (members[memberIndex].total_payments || 0) + amountNum;
    members[memberIndex].balance_owed = Math.max(0, (members[memberIndex].dues_fee_required || 3900) - members[memberIndex].dues_paid);
    saveMembers(members);
  }

  return updated;
};

export const bulkAddContributions = (newContributionsList) => {
  const contributions = getContributions();
  const members = getMembers();

  const formattedNew = newContributionsList.map((c, idx) => ({
    id: 'c-bulk-' + Date.now() + '-' + idx,
    payment_date: c.payment_date || new Date().toISOString().split('T')[0],
    ...c
  }));

  const updatedContributions = [...formattedNew, ...contributions];
  localStorage.setItem('ony_contributions', JSON.stringify(updatedContributions));

  formattedNew.forEach(c => {
    const memberIndex = members.findIndex(m => m.id === c.member_id);
    if (memberIndex !== -1) {
      const amountNum = parseFloat(c.amount) || 0;
      if (c.contribution_type === 'Monthly Dues') {
        members[memberIndex].dues_paid = (members[memberIndex].dues_paid || 0) + amountNum;
      } else if (c.contribution_type === 'Special Levy') {
        members[memberIndex].levy_paid = (members[memberIndex].levy_paid || 0) + amountNum;
      }
      members[memberIndex].total_payments = (members[memberIndex].total_payments || 0) + amountNum;
      members[memberIndex].balance_owed = Math.max(0, (members[memberIndex].dues_fee_required || 3900) - members[memberIndex].dues_paid);
    }
  });

  saveMembers(members);
  return updatedContributions;
};
